CREATE TABLE "SR_CRYPTO" (
"ID" VARCHAR2(255 BYTE) NOT NULL,
"ENC_DATA_KEY" VARCHAR2(100 BYTE) NOT NULL,
"DESCRIPTION"  VARCHAR2(1000 BYTE),
"KEY_DATE" DATE NOT NULL,
CONSTRAINT "SR_CRYPTO_PK" PRIMARY KEY ("ID")
);

